version: '3.2'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
  backend:
    build: be/.
    restart: always
    environment:
      FLASK_ENV: development
    ports:
      - "5000:5000"
    volumes:
      - ./be:/app
      - ~/.aws:/root/.aws
    depends_on:
      - elasticsearch
  frontend:
    build: fe/.
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - database