version: "3.2"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.15.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      ELASTIC_PASSWORD: changeme
      discovery.type: single-node
  backend:
    build: be/.
    restart: always
    environment:
      FLASK_ENV: development
      S3_NAME: junhuisearch
      TIKA_CLIENT_ONLY: 1
      TIKA_SERVER_ENDPOINT: http://tika:9998
      ES_ENDPOINT: http://elasticsearch:9200
      ES_INDEX: doc
      S3_LINK: https://junhuisearch.s3.ap-southeast-1.amazonaws.com/
    ports:
      - "5000:5000"
    volumes:
      - ./be:/app
      - ~/.aws:/root/.aws
    depends_on:
      - elasticsearch
      - tika
  tika:
    image: apache/tika
    ports:
      - "9998:9998"
  frontend:
    build: fe/.
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
      - tika
