on: push
env:
  PROJECT_NAME: search
  S3_BUCKET: junhui-infra-bot #create a new s3 bucket

jobs:
  deploy:
    name: Deploy be
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: zip file
          sudo touch backup.tar.gz
          sudo tar --exclude='.git/*' --exclude='be/terraform/.terraform/*' --exclude='backup.tar.gz' --exclude='data' -zcvf backup.tar.gz .

      - name: sync s3
          INSTANCE_ID=$(aws ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId, Tags[?Key==`Name`], Tags[?Key==`$PROJECT_NAME`]][0][0]' --output text)
          aws s3 cp ./$PROJECT_NAME.tar.gz s3://$S3_BUCKET
          aws s3 sync s3://$PROJECT_NAME.tar.gz s3://$S3_BUCKET --delete
