on: push
env:
  PROJECT_NAME: search
  NAME: junhui-infra-bot #create a new s3 bucket

jobs:
  deploy:
    name: Deploy be
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Delete, Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: $NAME
          IMAGE_TAG: $PROJECT_NAME

      - name: zip file
        run: |
          sudo touch $PROJECT_NAME.tar.gz
          sudo tar --exclude='.git/*' --exclude='fe/node_modules' --exclude='$PROJECT_NAME.tar.gz' --exclude='data' -zcvf $PROJECT_NAME.tar.gz .

      - name: sync s3
        run: |
          INSTANCE_ID=$(aws ec2 describe-instances --query 'Reservations[].Instances[].[InstanceId, Tags[?Key==`Name`], Tags[?Key==`$PROJECT_NAME`]][0][0]' --output text)
          aws s3 cp ./$PROJECT_NAME.tar.gz s3://$NAME/$PROJECT_NAME.tar.gz
          aws ec2 stop-instances --instance-ids $INSTANCE_ID
          sleep 60
          aws ec2 start-instances --instance-ids $INSTANCE_ID
