on: push
env:
  PROJECT_NAME: search
  NAME: junhui-infra-bot #create a new s3 bucket
  WORKDIR: ./fe

jobs:
  deploy:
    name: Deploy be
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Delete, Build, tag, and push image to Amazon ECR
        id: build-image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        working-directory: $WORKDIR
        run: |
          docker build -t $ECR_REGISTRY/$NAME:$PROJECT_NAME .
          docker push $ECR_REGISTRY/$NAME:$PROJECT_NAME
